// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachSessionObserver(arg1, arg2, arg3, arg4) {
  return window['go']['pty']['Service']['AttachSessionObserver'](arg1, arg2, arg3, arg4);
}

export function Close(arg1) {
  return window['go']['pty']['Service']['Close'](arg1);
}

export function CloseAll() {
  return window['go']['pty']['Service']['CloseAll']();
}

export function DetachSessionObserver(arg1, arg2) {
  return window['go']['pty']['Service']['DetachSessionObserver'](arg1, arg2);
}

export function GetOutputHistory(arg1) {
  return window['go']['pty']['Service']['GetOutputHistory'](arg1);
}

export function GetOutputHistoryWithSeq(arg1) {
  return window['go']['pty']['Service']['GetOutputHistoryWithSeq'](arg1);
}

export function GetPtyDimensions(arg1) {
  return window['go']['pty']['Service']['GetPtyDimensions'](arg1);
}

export function IsRunning(arg1) {
  return window['go']['pty']['Service']['IsRunning'](arg1);
}

export function RegisterExitCallback(arg1, arg2, arg3) {
  return window['go']['pty']['Service']['RegisterExitCallback'](arg1, arg2, arg3);
}

export function RegisterOutputCallback(arg1, arg2, arg3) {
  return window['go']['pty']['Service']['RegisterOutputCallback'](arg1, arg2, arg3);
}

export function RegisterResizeCallback(arg1, arg2, arg3) {
  return window['go']['pty']['Service']['RegisterResizeCallback'](arg1, arg2, arg3);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['pty']['Service']['Resize'](arg1, arg2, arg3);
}

export function RunningCount() {
  return window['go']['pty']['Service']['RunningCount']();
}

export function SetContext(arg1) {
  return window['go']['pty']['Service']['SetContext'](arg1);
}

export function Start(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['pty']['Service']['Start'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartResolved(arg1, arg2) {
  return window['go']['pty']['Service']['StartResolved'](arg1, arg2);
}

export function UnregisterExitCallback(arg1, arg2) {
  return window['go']['pty']['Service']['UnregisterExitCallback'](arg1, arg2);
}

export function UnregisterOutputCallback(arg1, arg2) {
  return window['go']['pty']['Service']['UnregisterOutputCallback'](arg1, arg2);
}

export function UnregisterResizeCallback(arg1, arg2) {
  return window['go']['pty']['Service']['UnregisterResizeCallback'](arg1, arg2);
}

export function Write(arg1, arg2) {
  return window['go']['pty']['Service']['Write'](arg1, arg2);
}

export function WriteLarge(arg1, arg2) {
  return window['go']['pty']['Service']['WriteLarge'](arg1, arg2);
}
