// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {platform} from '../models';

export function AttachSessionObserver(arg1:string,arg2:string,arg3:any,arg4:any):Promise<Array<number>>;

export function Close(arg1:string):Promise<void>;

export function CloseAll():Promise<void>;

export function DetachSessionObserver(arg1:string,arg2:string):Promise<void>;

export function GetOutputHistory(arg1:string):Promise<Array<number>>;

export function GetOutputHistoryWithSeq(arg1:string):Promise<Array<number>>;

export function GetPtyDimensions(arg1:string):Promise<number>;

export function IsRunning(arg1:string):Promise<boolean>;

export function RegisterExitCallback(arg1:string,arg2:string,arg3:any):Promise<void>;

export function RegisterOutputCallback(arg1:string,arg2:string,arg3:any):Promise<void>;

export function RegisterResizeCallback(arg1:string,arg2:string,arg3:any):Promise<void>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RunningCount():Promise<number>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Start(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:number,arg7:number):Promise<number>;

export function StartResolved(arg1:string,arg2:platform.ResolvedLaunchSpec):Promise<number>;

export function UnregisterExitCallback(arg1:string,arg2:string):Promise<void>;

export function UnregisterOutputCallback(arg1:string,arg2:string):Promise<void>;

export function UnregisterResizeCallback(arg1:string,arg2:string):Promise<void>;

export function Write(arg1:string,arg2:string):Promise<void>;

export function WriteLarge(arg1:string,arg2:string):Promise<void>;
