// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['updater']['Service']['CheckForUpdate']();
}

export function CleanupOldBinary() {
  return window['go']['updater']['Service']['CleanupOldBinary']();
}

export function DownloadAndApply(arg1) {
  return window['go']['updater']['Service']['DownloadAndApply'](arg1);
}

export function SetToken(arg1) {
  return window['go']['updater']['Service']['SetToken'](arg1);
}
