// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {headroom} from '../models';

export function GetPort():Promise<number>;

export function GetStatus():Promise<headroom.HeadroomStatus>;

export function IsRunning():Promise<boolean>;

export function Start(arg1:string):Promise<void>;

export function Stop():Promise<void>;
