// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort() {
  return window['go']['headroom']['HeadroomService']['GetPort']();
}

export function GetStatus() {
  return window['go']['headroom']['HeadroomService']['GetStatus']();
}

export function IsRunning() {
  return window['go']['headroom']['HeadroomService']['IsRunning']();
}

export function Start(arg1) {
  return window['go']['headroom']['HeadroomService']['Start'](arg1);
}

export function Stop() {
  return window['go']['headroom']['HeadroomService']['Stop']();
}
