// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {headroom} from '../models';

export function GetPort():Promise<number>;

export function GetSavings(arg1:context.Context):Promise<headroom.SavingsReport>;

export function GetStatus():Promise<headroom.HeadroomStatus>;

export function IsRunning():Promise<boolean>;

export function SetVenvBinDir(arg1:string):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function Stop():Promise<void>;
