// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitassist} from '../models';

export function CommitAll(arg1:string,arg2:string):Promise<void>;

export function CommitStaged(arg1:string,arg2:string):Promise<void>;

export function ListBranches(arg1:string):Promise<Array<gitassist.BranchInfo>>;

export function Push(arg1:string):Promise<string>;

export function RepoInfo(arg1:string):Promise<gitassist.RepoStatus>;

export function SummarizeDiff(arg1:string):Promise<string>;

export function SwitchBranch(arg1:string,arg2:string):Promise<void>;
