// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitAll(arg1, arg2) {
  return window['go']['gitassist']['Service']['CommitAll'](arg1, arg2);
}

export function CommitStaged(arg1, arg2) {
  return window['go']['gitassist']['Service']['CommitStaged'](arg1, arg2);
}

export function ListBranches(arg1) {
  return window['go']['gitassist']['Service']['ListBranches'](arg1);
}

export function Push(arg1) {
  return window['go']['gitassist']['Service']['Push'](arg1);
}

export function RepoInfo(arg1) {
  return window['go']['gitassist']['Service']['RepoInfo'](arg1);
}

export function SummarizeDiff(arg1) {
  return window['go']['gitassist']['Service']['SummarizeDiff'](arg1);
}

export function SwitchBranch(arg1, arg2) {
  return window['go']['gitassist']['Service']['SwitchBranch'](arg1, arg2);
}
