// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAPIKey(arg1:string):Promise<void>;

export function GetAPIKey(arg1:string):Promise<string>;

export function GetAPIKeyWithFallback(arg1:string):Promise<string|string>;

export function GetAllProviders():Promise<Array<string>>;

export function GetKeyDiagnostics(arg1:Array<string>):Promise<Record<string, Record<string, string>>>;

export function GetMinimaxAPIKey():Promise<string>;

export function GetZhipuAPIKey():Promise<string>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function Load():Promise<void>;

export function Save():Promise<void>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetMinimaxAPIKey(arg1:string):Promise<void>;

export function SetZhipuAPIKey(arg1:string):Promise<void>;
