// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAPIKey(arg1) {
  return window['go']['secrets']['SecretsService']['DeleteAPIKey'](arg1);
}

export function GetAPIKey(arg1) {
  return window['go']['secrets']['SecretsService']['GetAPIKey'](arg1);
}

export function GetAPIKeyWithFallback(arg1) {
  return window['go']['secrets']['SecretsService']['GetAPIKeyWithFallback'](arg1);
}

export function GetAllProviders() {
  return window['go']['secrets']['SecretsService']['GetAllProviders']();
}

export function GetKeyDiagnostics(arg1) {
  return window['go']['secrets']['SecretsService']['GetKeyDiagnostics'](arg1);
}

export function HasAPIKey(arg1) {
  return window['go']['secrets']['SecretsService']['HasAPIKey'](arg1);
}

export function Load() {
  return window['go']['secrets']['SecretsService']['Load']();
}

export function ReplaceAll(arg1) {
  return window['go']['secrets']['SecretsService']['ReplaceAll'](arg1);
}

export function Save() {
  return window['go']['secrets']['SecretsService']['Save']();
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['secrets']['SecretsService']['SetAPIKey'](arg1, arg2);
}

export function Snapshot() {
  return window['go']['secrets']['SecretsService']['Snapshot']();
}
