// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAmagiConfig() {
  return window['go']['piconfig']['Service']['GetAmagiConfig']();
}

export function GetAmagiConfigPath() {
  return window['go']['piconfig']['Service']['GetAmagiConfigPath']();
}

export function GetAuthConfig() {
  return window['go']['piconfig']['Service']['GetAuthConfig']();
}

export function GetAuthConfigPath() {
  return window['go']['piconfig']['Service']['GetAuthConfigPath']();
}

export function GetModelsConfig() {
  return window['go']['piconfig']['Service']['GetModelsConfig']();
}

export function GetModelsConfigPath() {
  return window['go']['piconfig']['Service']['GetModelsConfigPath']();
}

export function GetPiModelCatalog() {
  return window['go']['piconfig']['Service']['GetPiModelCatalog']();
}

export function SaveAmagiConfig(arg1) {
  return window['go']['piconfig']['Service']['SaveAmagiConfig'](arg1);
}

export function SaveAuthConfig(arg1) {
  return window['go']['piconfig']['Service']['SaveAuthConfig'](arg1);
}

export function SaveModelsConfig(arg1) {
  return window['go']['piconfig']['Service']['SaveModelsConfig'](arg1);
}
