// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAmagiConfig() {
  return window['go']['piconfig']['Service']['GetAmagiConfig']();
}

export function GetAmagiConfigPath() {
  return window['go']['piconfig']['Service']['GetAmagiConfigPath']();
}

export function GetPiModelCatalog() {
  return window['go']['piconfig']['Service']['GetPiModelCatalog']();
}

export function SaveAmagiConfig(arg1) {
  return window['go']['piconfig']['Service']['SaveAmagiConfig'](arg1);
}
