// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAmagiConfig():Promise<string>;

export function GetAmagiConfigPath():Promise<string>;

export function GetModelsConfig():Promise<string>;

export function GetModelsConfigPath():Promise<string>;

export function GetPiModelCatalog():Promise<string>;

export function SaveAmagiConfig(arg1:string):Promise<void>;

export function SaveModelsConfig(arg1:string):Promise<void>;
