// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetHandler() {
  return window['go']['skins']['Service']['AssetHandler']();
}

export function GetSkinSettings() {
  return window['go']['skins']['Service']['GetSkinSettings']();
}

export function ImportSkinImage(arg1) {
  return window['go']['skins']['Service']['ImportSkinImage'](arg1);
}

export function ListSkins() {
  return window['go']['skins']['Service']['ListSkins']();
}

export function PickSkinImage() {
  return window['go']['skins']['Service']['PickSkinImage']();
}

export function RemoveSkin(arg1) {
  return window['go']['skins']['Service']['RemoveSkin'](arg1);
}

export function SetContext(arg1) {
  return window['go']['skins']['Service']['SetContext'](arg1);
}

export function SetSkinSettings(arg1) {
  return window['go']['skins']['Service']['SetSkinSettings'](arg1);
}
