// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {settings} from '../models';
import {skins} from '../models';
import {context} from '../models';

export function AssetHandler():Promise<http.Handler>;

export function GetSkinSettings():Promise<settings.SkinSettings>;

export function ImportSkinImage(arg1:string):Promise<skins.Skin>;

export function ListSkins():Promise<Array<skins.Skin>>;

export function PickSkinImage():Promise<skins.Skin>;

export function RemoveSkin(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSkinSettings(arg1:settings.SkinSettings):Promise<void>;
