/**
 * Usage Stats API
 * 封装 AI 模型用量与成本统计相关的后端调用。
 *
 * Directly wraps wailsjs/go/usage/Service (auto-generated by Wails).
 * 真实类型真相源：frontend/wailsjs/go/models.ts 的 usage namespace。
 * Type aliases below re-export the canonical wailsjs classes so callers share one source of truth.
 */

import {
  GetUsageSummary,
  GetDailyTrends,
  GetModelStats,
  GetProviderStats,
  GetRequestLogs,
  SyncSessionUsage,
  GetSyncState,
  GetModelPricing,
  UpsertModelPricing,
  DeleteModelPricing,
  ResetModelPricing,
  GetUnknownModels,
} from '../../wailsjs/go/usage/Service';
import { usage } from '../../wailsjs/go/models';

// === 类型别名（对齐 wailsjs 真实导出，是本模块的权威类型来源）===
// Type aliases mirroring the canonical wailsjs usage namespace.
export type SummaryFilter = usage.SummaryFilter;
export type TrendFilter = usage.TrendFilter;
export type StatFilter = usage.StatFilter;
export type LogFilter = usage.LogFilter;
export type Summary = usage.Summary;
export type DailyTrendPoint = usage.DailyTrendPoint;
export type ModelStat = usage.ModelStat;
export type ProviderStat = usage.ProviderStat;
export type UsageRecord = usage.UsageRecord;
export type SyncResult = usage.SyncResult;
export type SyncState = usage.SyncState;
export type ModelPricing = usage.ModelPricing;
export type UnknownModel = usage.UnknownModel;

/**
 * 构造一个空 SummaryFilter 的工厂，避免分散默认值。
 * Factory for a fresh SummaryFilter with safe defaults.
 * 默认 source=session_log：避免与 proxy 实时拦截双计（设计 §7.2）。
 */
export function createSummaryFilter(overrides: Partial<SummaryFilter> = {}): SummaryFilter {
  return {
    startDate: '',
    endDate: '',
    appType: '',
    // 默认仅 session_log：proxy 路径与 session_log 路径会重复入库，前端默认只看主路径。
    // Default to session_log only: proxy + session_log double-count by design, main path wins.
    source: 'session_log',
    provider: '',
    ...overrides,
  };
}

/**
 * 构造 StatFilter（与 SummaryFilter 同字段集）。
 */
export function createStatFilter(filter: SummaryFilter): StatFilter {
  return {
    startDate: filter.startDate || '',
    endDate: filter.endDate || '',
    appType: filter.appType || '',
    source: filter.source || '',
    provider: filter.provider || '',
  };
}

/**
 * 构造 TrendFilter（基于 SummaryFilter 追加 days/granularity）。
 */
export function createTrendFilter(filter: SummaryFilter, days = 30, granularity = 'day'): TrendFilter {
  return {
    startDate: filter.startDate || '',
    endDate: filter.endDate || '',
    appType: filter.appType || '',
    source: filter.source || '',
    provider: filter.provider || '',
    granularity,
    days,
  };
}

// === 查询类 / Read queries ===

/** 拉取累计汇总（总请求/总 token/各币种成本/主币种 USD 折算） */
export async function getUsageSummary(filter: SummaryFilter): Promise<Summary> {
  try {
    return await GetUsageSummary(filter);
  } catch (error) {
    console.error('[api.usage.getUsageSummary]', error);
    throw error;
  }
}

/** 拉取日趋势（最近 N 天，每日成本与 token） */
export async function getDailyTrends(filter: TrendFilter): Promise<DailyTrendPoint[]> {
  try {
    return await GetDailyTrends(filter);
  } catch (error) {
    console.error('[api.usage.getDailyTrends]', error);
    throw error;
  }
}

/** 模型维度统计（含 hasPrice 标记，用于无价格徽章） */
export async function getModelStats(filter: StatFilter): Promise<ModelStat[]> {
  try {
    return await GetModelStats(filter);
  } catch (error) {
    console.error('[api.usage.getModelStats]', error);
    throw error;
  }
}

/** 供应商维度统计（请求数/各币种成本/总 token/模型数） */
export async function getProviderStats(filter: StatFilter): Promise<ProviderStat[]> {
  try {
    return await GetProviderStats(filter);
  } catch (error) {
    console.error('[api.usage.getProviderStats]', error);
    throw error;
  }
}

/** 明细日志查询（分页） */
export async function getRequestLogs(filter: LogFilter): Promise<UsageRecord[]> {
  try {
    return await GetRequestLogs(filter);
  } catch (error) {
    console.error('[api.usage.getRequestLogs]', error);
    throw error;
  }
}

/** 未知模型列表（usage_records 中存在但价格表未匹配） */
export async function getUnknownModels(): Promise<UnknownModel[]> {
  try {
    return await GetUnknownModels();
  } catch (error) {
    console.error('[api.usage.getUnknownModels]', error);
    throw error;
  }
}

// === 同步类 / Sync ===

/** 触发一次阻塞同步（三类 CLI 源），返回结果摘要。「立即同步」按钮调用。 */
export async function syncSessionUsage(): Promise<SyncResult> {
  try {
    return await SyncSessionUsage();
  } catch (error) {
    console.error('[api.usage.syncSessionUsage]', error);
    throw error;
  }
}

/** 拉取各源的增量同步游标（用于状态展示） */
export async function getSyncState(): Promise<SyncState[]> {
  try {
    return await GetSyncState();
  } catch (error) {
    console.error('[api.usage.getSyncState]', error);
    throw error;
  }
}

// === 价格表 CRUD / Pricing table CRUD ===

/** 列出全部价格表条目（内置 + 自定义） */
export async function getModelPricing(): Promise<ModelPricing[]> {
  try {
    return await GetModelPricing();
  } catch (error) {
    console.error('[api.usage.getModelPricing]', error);
    throw error;
  }
}

/** 新增/更新一条价格（按 id 覆盖；isBuiltin 模型也可改价） */
export async function upsertModelPricing(mp: ModelPricing): Promise<void> {
  try {
    await UpsertModelPricing(mp);
  } catch (error) {
    console.error('[api.usage.upsertModelPricing]', error);
    throw error;
  }
}

/** 删除一条自定义价格（内置模型后端会拒绝） */
export async function deleteModelPricing(id: string): Promise<void> {
  try {
    await DeleteModelPricing(id);
  } catch (error) {
    console.error('[api.usage.deleteModelPricing]', error);
    throw error;
  }
}

/** 恢复内置价格表 seed */
export async function resetModelPricing(): Promise<void> {
  try {
    await ResetModelPricing();
  } catch (error) {
    console.error('[api.usage.resetModelPricing]', error);
    throw error;
  }
}
