/**
 * Usage Stats API
 * 封装 AI 模型用量与成本统计相关的后端调用。
 *
 * Directly wraps wailsjs/go/usage/Service (auto-generated by Wails).
 * 真实类型真相源：frontend/wailsjs/go/models.ts 的 usage namespace。
 * Type aliases below re-export the canonical wailsjs classes so callers share one source of truth.
 */

import {
  GetUsageSummary,
  GetDailyTrends,
  GetModelDailyTrends,
  GetModelStats,
  GetProviderStats,
  GetRequestLogs,
  SyncSessionUsage,
  GetSyncState,
  GetModelPricing,
  UpsertModelPricing,
  DeleteModelPricing,
  ResetModelPricing,
  GetUnknownModels,
} from '../../wailsjs/go/usage/Service';
import { usage } from '../../wailsjs/go/models';
import { callApi } from './internal/call';

// === 类型别名（对齐 wailsjs 真实导出，是本模块的权威类型来源）===
// Type aliases mirroring the canonical wailsjs usage namespace.
export type SummaryFilter = usage.SummaryFilter;
export type TrendFilter = usage.TrendFilter;
export type StatFilter = usage.StatFilter;
export type LogFilter = usage.LogFilter;
export type Summary = usage.Summary;
export type DailyTrendPoint = usage.DailyTrendPoint;
export type ModelDailyTrendPoint = usage.ModelDailyTrendPoint;
export type ModelStat = usage.ModelStat;
export type ProviderStat = usage.ProviderStat;
export type UsageRecord = usage.UsageRecord;
export type SyncResult = usage.SyncResult;
export type SyncState = usage.SyncState;
export type ModelPricing = usage.ModelPricing;
export type UnknownModel = usage.UnknownModel;

/**
 * 构造带默认筛选条件的 SummaryFilter，避免分散默认值。
 * Factory for a fresh SummaryFilter with safe defaults.
 * 默认使用会话日志数据源。
 */
export type UsageRangePreset = 'today' | '7d' | '30d' | 'month' | 'custom';

export interface UsageDateRange {
  startDate: string;
  endDate: string;
}

function toUTCDateString(value: Date): string {
  return value.toISOString().slice(0, 10);
}

/** Resolve a named dashboard period into an inclusive UTC date range. */
export function resolveUsageRange(preset: Exclude<UsageRangePreset, 'custom'>, now = new Date()): UsageDateRange {
  const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
  const start = new Date(end);
  switch (preset) {
    case 'today':
      break;
    case '7d':
      start.setUTCDate(start.getUTCDate() - 6);
      break;
    case '30d':
      start.setUTCDate(start.getUTCDate() - 29);
      break;
    case 'month':
      start.setUTCDate(1);
      break;
  }
  return { startDate: toUTCDateString(start), endDate: toUTCDateString(end) };
}

export function createSummaryFilter(overrides: Partial<SummaryFilter> = {}): SummaryFilter {
  const defaultRange = resolveUsageRange('30d');
  return {
    startDate: defaultRange.startDate,
    endDate: defaultRange.endDate,
    appType: '',
    // 会话日志是当前唯一的用量采集路径。
    source: 'session_log',
    provider: '',
    ...overrides,
  };
}

/**
 * 构造 StatFilter（与 SummaryFilter 同字段集）。
 */
export function createStatFilter(filter: SummaryFilter): StatFilter {
  return {
    startDate: filter.startDate || '',
    endDate: filter.endDate || '',
    appType: filter.appType || '',
    source: filter.source || '',
    provider: filter.provider || '',
  };
}

/**
 * 构造 TrendFilter（基于 SummaryFilter 追加 days/granularity）。
 */
export function createTrendFilter(filter: SummaryFilter, days = 30, granularity = 'day'): TrendFilter {
  return {
    startDate: filter.startDate || '',
    endDate: filter.endDate || '',
    appType: filter.appType || '',
    source: filter.source || '',
    provider: filter.provider || '',
    granularity,
    days,
  };
}

// === 查询类 / Read queries ===

/** 拉取累计汇总（总请求/总 token/各币种成本/主币种 USD 折算） */
export function getUsageSummary(filter: SummaryFilter): Promise<Summary> {
  return callApi('[api.usage.getUsageSummary]', () => GetUsageSummary(filter));
}

/** 拉取日趋势（最近 N 天，每日成本与 token） */
export function getDailyTrends(filter: TrendFilter): Promise<DailyTrendPoint[]> {
  return callApi('[api.usage.getDailyTrends]', () => GetDailyTrends(filter));
}

/** Per-model daily trends. Each model remains an independent curve. */
export function getModelDailyTrends(filter: TrendFilter): Promise<ModelDailyTrendPoint[]> {
  return callApi('[api.usage.getModelDailyTrends]', () => GetModelDailyTrends(filter));
}

/** 模型维度统计（含 hasPrice 标记，用于无价格徽章） */
export function getModelStats(filter: StatFilter): Promise<ModelStat[]> {
  return callApi('[api.usage.getModelStats]', () => GetModelStats(filter));
}

/** 供应商维度统计（请求数/各币种成本/总 token/模型数） */
export function getProviderStats(filter: StatFilter): Promise<ProviderStat[]> {
  return callApi('[api.usage.getProviderStats]', () => GetProviderStats(filter));
}

/** 明细日志查询（分页） */
export function getRequestLogs(filter: LogFilter): Promise<UsageRecord[]> {
  return callApi('[api.usage.getRequestLogs]', () => GetRequestLogs(filter));
}

/** 未知模型列表（usage_records 中存在但价格表未匹配） */
export function getUnknownModels(): Promise<UnknownModel[]> {
  return callApi('[api.usage.getUnknownModels]', () => GetUnknownModels());
}

// === 同步类 / Sync ===

/** 触发一次阻塞同步（三类 CLI 源），返回结果摘要。「立即同步」按钮调用。 */
export function syncSessionUsage(): Promise<SyncResult> {
  return callApi('[api.usage.syncSessionUsage]', () => SyncSessionUsage());
}

/** 拉取各源的增量同步游标（用于状态展示） */
export function getSyncState(): Promise<SyncState[]> {
  return callApi('[api.usage.getSyncState]', () => GetSyncState());
}

// === 价格表 CRUD / Pricing table CRUD ===

/** 列出全部价格表条目（内置 + 自定义） */
export function getModelPricing(): Promise<ModelPricing[]> {
  return callApi('[api.usage.getModelPricing]', () => GetModelPricing());
}

/** 新增/更新一条价格（按 id 覆盖；isBuiltin 模型也可改价） */
export function upsertModelPricing(mp: ModelPricing): Promise<void> {
  return callApi('[api.usage.upsertModelPricing]', () => UpsertModelPricing(mp));
}

/** 删除一条自定义价格（内置模型后端会拒绝） */
export function deleteModelPricing(id: string): Promise<void> {
  return callApi('[api.usage.deleteModelPricing]', () => DeleteModelPricing(id));
}

/** 恢复内置价格表 seed */
export function resetModelPricing(): Promise<void> {
  return callApi('[api.usage.resetModelPricing]', () => ResetModelPricing());
}
