// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOpenCodeConfig():Promise<string>;

export function GetOpenCodeConfigPath():Promise<string>;

export function SaveOpenCodeConfig(arg1:string):Promise<void>;

export function SyncManagedProviders(arg1:Record<string, any>):Promise<void>;
