// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOpenCodeConfig() {
  return window['go']['opencodeconfig']['Service']['GetOpenCodeConfig']();
}

export function GetOpenCodeConfigPath() {
  return window['go']['opencodeconfig']['Service']['GetOpenCodeConfigPath']();
}

export function SaveOpenCodeConfig(arg1) {
  return window['go']['opencodeconfig']['Service']['SaveOpenCodeConfig'](arg1);
}
