// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPackageDetails(arg1) {
  return window['go']['piplugin']['Service']['GetPackageDetails'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['piplugin']['Service']['InstallPackage'](arg1);
}

export function ListInstalledPackages() {
  return window['go']['piplugin']['Service']['ListInstalledPackages']();
}

export function RefreshPackages() {
  return window['go']['piplugin']['Service']['RefreshPackages']();
}

export function RemovePackage(arg1) {
  return window['go']['piplugin']['Service']['RemovePackage'](arg1);
}

export function SwitchPackageSource(arg1, arg2) {
  return window['go']['piplugin']['Service']['SwitchPackageSource'](arg1, arg2);
}

export function UpdatePackage(arg1) {
  return window['go']['piplugin']['Service']['UpdatePackage'](arg1);
}
