// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {piplugin} from '../models';

export function GetPackageDetails(arg1:string):Promise<piplugin.PackageDetail>;

export function InstallPackage(arg1:string):Promise<piplugin.CommandResult>;

export function ListInstalledPackages():Promise<Array<piplugin.Package>>;

export function RefreshPackages():Promise<piplugin.PackagesData>;

export function RemovePackage(arg1:string):Promise<piplugin.CommandResult>;

export function SwitchPackageSource(arg1:string,arg2:string):Promise<piplugin.CommandResult>;

export function UpdatePackage(arg1:string):Promise<piplugin.CommandResult>;
