// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAgentProfile(arg1:string):Promise<void>;

export function CaptureAgentProfile(arg1:string):Promise<void>;

export function DeleteAgentProfile(arg1:string):Promise<void>;

export function GetAgentProfile(arg1:string):Promise<string>;

export function ListAgentProfiles():Promise<string>;

export function SaveAgentProfile(arg1:string,arg2:string,arg3:string):Promise<void>;
