// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAgentProfile(arg1) {
  return window['go']['agentprofile']['Service']['ApplyAgentProfile'](arg1);
}

export function CaptureAgentProfile(arg1) {
  return window['go']['agentprofile']['Service']['CaptureAgentProfile'](arg1);
}

export function DeleteAgentProfile(arg1) {
  return window['go']['agentprofile']['Service']['DeleteAgentProfile'](arg1);
}

export function GetAgentProfile(arg1) {
  return window['go']['agentprofile']['Service']['GetAgentProfile'](arg1);
}

export function ListAgentProfiles() {
  return window['go']['agentprofile']['Service']['ListAgentProfiles']();
}

export function SaveAgentProfile(arg1, arg2, arg3) {
  return window['go']['agentprofile']['Service']['SaveAgentProfile'](arg1, arg2, arg3);
}
