// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';

export function BuildScaffold(arg1:string):Promise<workspace.DeployResult>;

export function CheckConflicts(arg1:string,arg2:string,arg3:string):Promise<Array<workspace.Conflict>>;

export function CleanWorkspace(arg1:string):Promise<workspace.CleanResult>;

export function CreateWorkspace(arg1:string,arg2:string,arg3:Array<workspace.ToolType>):Promise<workspace.Workspace>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetAvailablePluginsForWorkspace(arg1:string):Promise<Array<workspace.AvailablePlugin>>;

export function GetDeploymentManifest(arg1:string):Promise<workspace.DeploymentManifest>;

export function GetGlobalEnabled():Promise<Array<workspace.GlobalEnabled>>;

export function GetWorkspace(arg1:string):Promise<workspace.Workspace>;

export function ListWorkspaces():Promise<Array<workspace.Workspace>>;

export function Load():Promise<void>;

export function Save():Promise<void>;

export function SetGlobalEnabled(arg1:Array<workspace.GlobalEnabled>):Promise<workspace.DeployResult>;

export function SetWorkspacePlugins(arg1:string,arg2:Array<workspace.WorkspacePlugin>):Promise<void>;

export function SyncWorkspace(arg1:string):Promise<workspace.DeployResult>;

export function UpdateWorkspace(arg1:string,arg2:string,arg3:string,arg4:Array<workspace.ToolType>):Promise<workspace.Workspace>;
