// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildScaffold(arg1) {
  return window['go']['workspace']['Service']['BuildScaffold'](arg1);
}

export function CheckConflicts(arg1, arg2, arg3) {
  return window['go']['workspace']['Service']['CheckConflicts'](arg1, arg2, arg3);
}

export function CleanWorkspace(arg1) {
  return window['go']['workspace']['Service']['CleanWorkspace'](arg1);
}

export function CreateWorkspace(arg1, arg2, arg3) {
  return window['go']['workspace']['Service']['CreateWorkspace'](arg1, arg2, arg3);
}

export function DeleteWorkspace(arg1) {
  return window['go']['workspace']['Service']['DeleteWorkspace'](arg1);
}

export function GetAvailablePluginsForWorkspace(arg1) {
  return window['go']['workspace']['Service']['GetAvailablePluginsForWorkspace'](arg1);
}

export function GetDeploymentManifest(arg1) {
  return window['go']['workspace']['Service']['GetDeploymentManifest'](arg1);
}

export function GetGlobalEnabled() {
  return window['go']['workspace']['Service']['GetGlobalEnabled']();
}

export function GetWorkspace(arg1) {
  return window['go']['workspace']['Service']['GetWorkspace'](arg1);
}

export function ListWorkspaces() {
  return window['go']['workspace']['Service']['ListWorkspaces']();
}

export function Load() {
  return window['go']['workspace']['Service']['Load']();
}

export function Save() {
  return window['go']['workspace']['Service']['Save']();
}

export function SetGlobalEnabled(arg1) {
  return window['go']['workspace']['Service']['SetGlobalEnabled'](arg1);
}

export function SetWorkspacePlugins(arg1, arg2) {
  return window['go']['workspace']['Service']['SetWorkspacePlugins'](arg1, arg2);
}

export function SyncWorkspace(arg1) {
  return window['go']['workspace']['Service']['SyncWorkspace'](arg1);
}

export function UpdateWorkspace(arg1, arg2, arg3, arg4) {
  return window['go']['workspace']['Service']['UpdateWorkspace'](arg1, arg2, arg3, arg4);
}
