// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModelsConfig() {
  return window['go']['ompconfig']['Service']['GetModelsConfig']();
}

export function GetModelsConfigPath() {
  return window['go']['ompconfig']['Service']['GetModelsConfigPath']();
}

export function GetOmpConfig() {
  return window['go']['ompconfig']['Service']['GetOmpConfig']();
}

export function GetOmpConfigPath() {
  return window['go']['ompconfig']['Service']['GetOmpConfigPath']();
}

export function GetOmpModelCatalog() {
  return window['go']['ompconfig']['Service']['GetOmpModelCatalog']();
}

export function SaveModelsConfig(arg1) {
  return window['go']['ompconfig']['Service']['SaveModelsConfig'](arg1);
}

export function SaveOmpConfig(arg1) {
  return window['go']['ompconfig']['Service']['SaveOmpConfig'](arg1);
}
