// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOmpConfig():Promise<string>;

export function GetOmpConfigPath():Promise<string>;

export function GetOmpModelCatalog():Promise<string>;

export function SaveOmpConfig(arg1:string):Promise<void>;
