// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddUrlToHistory(arg1:string,arg2:string):Promise<void>;

export function DeleteOpenCodePreset(arg1:string):Promise<void>;

export function DeletePreset(arg1:string,arg2:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteTerminalPreset(arg1:string,arg2:string):Promise<void>;

export function GetAgentTeams():Promise<config.AgentTeamsConfig>;

export function GetAllTerminalPresets():Promise<config.TerminalPresetsConfig>;

export function GetConfig():Promise<config.AppConfig>;

export function GetMergedTerminalPresets(arg1:string):Promise<Array<config.MergedTerminalPreset>>;

export function GetOpenCodePreset(arg1:string):Promise<config.OpenCodePreset>;

export function GetOpenCodePresets():Promise<Record<string, config.OpenCodePreset>>;

export function GetPresets(arg1:string):Promise<Record<string, config.Preset>>;

export function GetProvider(arg1:string):Promise<config.Provider>;

export function GetProviderNames():Promise<Array<string>>;

export function GetProviders():Promise<Record<string, config.Provider>>;

export function GetTerminalPresets(arg1:string):Promise<Record<string, config.TerminalPreset>>;

export function GetUrlHistory(arg1:string):Promise<Array<string>>;

export function Load():Promise<void>;

export function MigrateProviderPresetsToTerminal():Promise<number>;

export function RemoveUrlFromHistory(arg1:string,arg2:string):Promise<void>;

export function ResolveTerminalPreset(arg1:string,arg2:string):Promise<string>;

export function Save():Promise<void>;

export function SaveOpenCodePreset(arg1:string,arg2:config.OpenCodePreset):Promise<void>;

export function SavePreset(arg1:string,arg2:string,arg3:config.Preset):Promise<void>;

export function SaveProvider(arg1:string,arg2:config.Provider):Promise<void>;

export function SaveTerminalPreset(arg1:string,arg2:string,arg3:config.TerminalPreset):Promise<void>;

export function SetAgentTeams(arg1:config.AgentTeamsConfig):Promise<void>;

export function SetAllTerminalPresets(arg1:config.TerminalPresetsConfig):Promise<void>;
