// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUrlToHistory(arg1, arg2) {
  return window['go']['config']['ConfigService']['AddUrlToHistory'](arg1, arg2);
}

export function DeletePreset(arg1, arg2) {
  return window['go']['config']['ConfigService']['DeletePreset'](arg1, arg2);
}

export function DeleteProvider(arg1) {
  return window['go']['config']['ConfigService']['DeleteProvider'](arg1);
}

export function GetAgentTeams() {
  return window['go']['config']['ConfigService']['GetAgentTeams']();
}

export function GetConfig() {
  return window['go']['config']['ConfigService']['GetConfig']();
}

export function GetPresets(arg1) {
  return window['go']['config']['ConfigService']['GetPresets'](arg1);
}

export function GetProvider(arg1) {
  return window['go']['config']['ConfigService']['GetProvider'](arg1);
}

export function GetProviderNames() {
  return window['go']['config']['ConfigService']['GetProviderNames']();
}

export function GetProviders() {
  return window['go']['config']['ConfigService']['GetProviders']();
}

export function GetUrlHistory(arg1) {
  return window['go']['config']['ConfigService']['GetUrlHistory'](arg1);
}

export function Load() {
  return window['go']['config']['ConfigService']['Load']();
}

export function RemoveUrlFromHistory(arg1, arg2) {
  return window['go']['config']['ConfigService']['RemoveUrlFromHistory'](arg1, arg2);
}

export function Save() {
  return window['go']['config']['ConfigService']['Save']();
}

export function SavePreset(arg1, arg2, arg3) {
  return window['go']['config']['ConfigService']['SavePreset'](arg1, arg2, arg3);
}

export function SaveProvider(arg1, arg2) {
  return window['go']['config']['ConfigService']['SaveProvider'](arg1, arg2);
}

export function SetAgentTeams(arg1) {
  return window['go']['config']['ConfigService']['SetAgentTeams'](arg1);
}
