// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUrlToHistory(arg1, arg2) {
  return window['go']['config']['ConfigService']['AddUrlToHistory'](arg1, arg2);
}

export function DeleteOpenCodePreset(arg1) {
  return window['go']['config']['ConfigService']['DeleteOpenCodePreset'](arg1);
}

export function DeletePreset(arg1, arg2) {
  return window['go']['config']['ConfigService']['DeletePreset'](arg1, arg2);
}

export function DeleteProvider(arg1) {
  return window['go']['config']['ConfigService']['DeleteProvider'](arg1);
}

export function DeleteTerminalPreset(arg1, arg2) {
  return window['go']['config']['ConfigService']['DeleteTerminalPreset'](arg1, arg2);
}

export function GetAgentTeams() {
  return window['go']['config']['ConfigService']['GetAgentTeams']();
}

export function GetAllOpenCodePresets() {
  return window['go']['config']['ConfigService']['GetAllOpenCodePresets']();
}

export function GetAllTerminalPresets() {
  return window['go']['config']['ConfigService']['GetAllTerminalPresets']();
}

export function GetConfig() {
  return window['go']['config']['ConfigService']['GetConfig']();
}

export function GetMergedTerminalPresets(arg1) {
  return window['go']['config']['ConfigService']['GetMergedTerminalPresets'](arg1);
}

export function GetOpenCodePreset(arg1) {
  return window['go']['config']['ConfigService']['GetOpenCodePreset'](arg1);
}

export function GetOpenCodePresets() {
  return window['go']['config']['ConfigService']['GetOpenCodePresets']();
}

export function GetPresets(arg1) {
  return window['go']['config']['ConfigService']['GetPresets'](arg1);
}

export function GetProvider(arg1) {
  return window['go']['config']['ConfigService']['GetProvider'](arg1);
}

export function GetProviderNames() {
  return window['go']['config']['ConfigService']['GetProviderNames']();
}

export function GetProviders() {
  return window['go']['config']['ConfigService']['GetProviders']();
}

export function GetTerminalPresets(arg1) {
  return window['go']['config']['ConfigService']['GetTerminalPresets'](arg1);
}

export function GetUrlHistory(arg1) {
  return window['go']['config']['ConfigService']['GetUrlHistory'](arg1);
}

export function Load() {
  return window['go']['config']['ConfigService']['Load']();
}

export function MigrateProviderPresetsToTerminal() {
  return window['go']['config']['ConfigService']['MigrateProviderPresetsToTerminal']();
}

export function RemoveUrlFromHistory(arg1, arg2) {
  return window['go']['config']['ConfigService']['RemoveUrlFromHistory'](arg1, arg2);
}

export function ReplaceImportedPresetSnapshots(arg1, arg2, arg3) {
  return window['go']['config']['ConfigService']['ReplaceImportedPresetSnapshots'](arg1, arg2, arg3);
}

export function ResolveTerminalPreset(arg1, arg2) {
  return window['go']['config']['ConfigService']['ResolveTerminalPreset'](arg1, arg2);
}

export function Save() {
  return window['go']['config']['ConfigService']['Save']();
}

export function SaveOpenCodePreset(arg1, arg2) {
  return window['go']['config']['ConfigService']['SaveOpenCodePreset'](arg1, arg2);
}

export function SavePreset(arg1, arg2, arg3) {
  return window['go']['config']['ConfigService']['SavePreset'](arg1, arg2, arg3);
}

export function SaveProvider(arg1, arg2) {
  return window['go']['config']['ConfigService']['SaveProvider'](arg1, arg2);
}

export function SaveTerminalPreset(arg1, arg2, arg3) {
  return window['go']['config']['ConfigService']['SaveTerminalPreset'](arg1, arg2, arg3);
}

export function SetAgentTeams(arg1) {
  return window['go']['config']['ConfigService']['SetAgentTeams'](arg1);
}

export function SetAllTerminalPresets(arg1) {
  return window['go']['config']['ConfigService']['SetAllTerminalPresets'](arg1);
}
