// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {opencodeplugin} from '../models';

export function GetPluginDetails(arg1:string):Promise<opencodeplugin.PluginDetail>;

export function InstallPlugin(arg1:string):Promise<opencodeplugin.CommandResult>;

export function ListInstalledPlugins():Promise<Array<opencodeplugin.Plugin>>;

export function RefreshPlugins():Promise<opencodeplugin.PluginsData>;

export function UninstallPlugin(arg1:string):Promise<opencodeplugin.CommandResult>;

export function UpdatePlugin(arg1:string):Promise<opencodeplugin.CommandResult>;
