// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPluginDetails(arg1) {
  return window['go']['opencodeplugin']['Service']['GetPluginDetails'](arg1);
}

export function InstallPlugin(arg1) {
  return window['go']['opencodeplugin']['Service']['InstallPlugin'](arg1);
}

export function ListInstalledPlugins() {
  return window['go']['opencodeplugin']['Service']['ListInstalledPlugins']();
}

export function RefreshPlugins() {
  return window['go']['opencodeplugin']['Service']['RefreshPlugins']();
}

export function UninstallPlugin(arg1) {
  return window['go']['opencodeplugin']['Service']['UninstallPlugin'](arg1);
}

export function UpdatePlugin(arg1) {
  return window['go']['opencodeplugin']['Service']['UpdatePlugin'](arg1);
}
