// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackendURL(arg1) {
  return window['go']['proxy']['ProxyService']['AddBackendURL'](arg1);
}

export function AddRule(arg1) {
  return window['go']['proxy']['ProxyService']['AddRule'](arg1);
}

export function ClearCurrentSession() {
  return window['go']['proxy']['ProxyService']['ClearCurrentSession']();
}

export function DeleteRule(arg1) {
  return window['go']['proxy']['ProxyService']['DeleteRule'](arg1);
}

export function GetBackendURLHistory() {
  return window['go']['proxy']['ProxyService']['GetBackendURLHistory']();
}

export function GetLogs() {
  return window['go']['proxy']['ProxyService']['GetLogs']();
}

export function GetPort() {
  return window['go']['proxy']['ProxyService']['GetPort']();
}

export function GetRules() {
  return window['go']['proxy']['ProxyService']['GetRules']();
}

export function GetStatus() {
  return window['go']['proxy']['ProxyService']['GetStatus']();
}

export function IsRunning() {
  return window['go']['proxy']['ProxyService']['IsRunning']();
}

export function LoadBackendURLHistory(arg1) {
  return window['go']['proxy']['ProxyService']['LoadBackendURLHistory'](arg1);
}

export function LoadRules(arg1) {
  return window['go']['proxy']['ProxyService']['LoadRules'](arg1);
}

export function RemoveBackendURL(arg1) {
  return window['go']['proxy']['ProxyService']['RemoveBackendURL'](arg1);
}

export function SaveBackendURLHistory(arg1) {
  return window['go']['proxy']['ProxyService']['SaveBackendURLHistory'](arg1);
}

export function SaveRules(arg1) {
  return window['go']['proxy']['ProxyService']['SaveRules'](arg1);
}

export function SetBackendURL(arg1) {
  return window['go']['proxy']['ProxyService']['SetBackendURL'](arg1);
}

export function SetCurrentSession(arg1, arg2, arg3, arg4) {
  return window['go']['proxy']['ProxyService']['SetCurrentSession'](arg1, arg2, arg3, arg4);
}

export function SetRules(arg1) {
  return window['go']['proxy']['ProxyService']['SetRules'](arg1);
}

export function SetUsageSink(arg1) {
  return window['go']['proxy']['ProxyService']['SetUsageSink'](arg1);
}

export function Start(arg1, arg2) {
  return window['go']['proxy']['ProxyService']['Start'](arg1, arg2);
}

export function Stop() {
  return window['go']['proxy']['ProxyService']['Stop']();
}

export function UpdateRule(arg1) {
  return window['go']['proxy']['ProxyService']['UpdateRule'](arg1);
}
