// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';

export function AddBackendURL(arg1:string):Promise<void>;

export function AddRule(arg1:proxy.InjectionRule):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetBackendURLHistory():Promise<Array<string>>;

export function GetLogs():Promise<Array<proxy.InjectionLog>>;

export function GetPort():Promise<number>;

export function GetRules():Promise<Array<proxy.InjectionRule>>;

export function GetStatus():Promise<proxy.ProxyStatus>;

export function IsRunning():Promise<boolean>;

export function LoadBackendURLHistory(arg1:string):Promise<void>;

export function LoadRules(arg1:string):Promise<void>;

export function RemoveBackendURL(arg1:string):Promise<void>;

export function SaveBackendURLHistory(arg1:string):Promise<void>;

export function SaveRules(arg1:string):Promise<void>;

export function SetBackendURL(arg1:string):Promise<void>;

export function SetRules(arg1:Array<proxy.InjectionRule>):Promise<void>;

export function Start(arg1:number,arg2:string):Promise<void>;

export function Stop():Promise<void>;

export function UpdateRule(arg1:proxy.InjectionRule):Promise<void>;
