// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ompplugin} from '../models';

export function InstallPlugin(arg1:string):Promise<ompplugin.CommandResult>;

export function ListPlugins():Promise<Array<ompplugin.Plugin>>;

export function RefreshPlugins():Promise<ompplugin.PluginsData>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<ompplugin.CommandResult>;

export function UninstallPlugin(arg1:string):Promise<ompplugin.CommandResult>;

export function UpgradePlugin(arg1:string):Promise<ompplugin.CommandResult>;
