// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallPlugin(arg1) {
  return window['go']['ompplugin']['Service']['InstallPlugin'](arg1);
}

export function ListPlugins() {
  return window['go']['ompplugin']['Service']['ListPlugins']();
}

export function RefreshPlugins() {
  return window['go']['ompplugin']['Service']['RefreshPlugins']();
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['ompplugin']['Service']['SetPluginEnabled'](arg1, arg2);
}

export function UninstallPlugin(arg1) {
  return window['go']['ompplugin']['Service']['UninstallPlugin'](arg1);
}

export function UpgradePlugin(arg1) {
  return window['go']['ompplugin']['Service']['UpgradePlugin'](arg1);
}
