// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {envcheck} from '../models';

export function CheckAll():Promise<envcheck.OverallStatus>;

export function CheckLatestVersion(arg1:envcheck.CLITool):Promise<string>;

export function CheckOne(arg1:envcheck.CLITool):Promise<envcheck.CheckStatus>;

export function GetCachedStatus():Promise<envcheck.OverallStatus>;

export function Install(arg1:envcheck.CLITool):Promise<envcheck.InstallResult>;

export function Update(arg1:envcheck.CLITool):Promise<envcheck.InstallResult>;
