// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAll() {
  return window['go']['envcheck']['Service']['CheckAll']();
}

export function CheckLatestVersion(arg1) {
  return window['go']['envcheck']['Service']['CheckLatestVersion'](arg1);
}

export function CheckOne(arg1) {
  return window['go']['envcheck']['Service']['CheckOne'](arg1);
}

export function GetCachedStatus() {
  return window['go']['envcheck']['Service']['GetCachedStatus']();
}

export function Install(arg1) {
  return window['go']['envcheck']['Service']['Install'](arg1);
}

export function Update(arg1) {
  return window['go']['envcheck']['Service']['Update'](arg1);
}
