// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logging} from '../models';

export function ClearEntries():Promise<void>;

export function Close():Promise<void>;

export function Debug(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function Error(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function ExportJSON():Promise<string>;

export function GetEntries(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<logging.Entry>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetSources():Promise<Array<string>>;

export function Info(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function Warn(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
