// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearEntries() {
  return window['go']['logging']['Service']['ClearEntries']();
}

export function Close() {
  return window['go']['logging']['Service']['Close']();
}

export function Debug(arg1, arg2, arg3) {
  return window['go']['logging']['Service']['Debug'](arg1, arg2, arg3);
}

export function Error(arg1, arg2, arg3) {
  return window['go']['logging']['Service']['Error'](arg1, arg2, arg3);
}

export function ExportJSON() {
  return window['go']['logging']['Service']['ExportJSON']();
}

export function GetEntries(arg1, arg2, arg3, arg4) {
  return window['go']['logging']['Service']['GetEntries'](arg1, arg2, arg3, arg4);
}

export function GetLogFileContent(arg1) {
  return window['go']['logging']['Service']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['logging']['Service']['GetLogFiles']();
}

export function GetSources() {
  return window['go']['logging']['Service']['GetSources']();
}

export function Info(arg1, arg2, arg3) {
  return window['go']['logging']['Service']['Info'](arg1, arg2, arg3);
}

export function Warn(arg1, arg2, arg3) {
  return window['go']['logging']['Service']['Warn'](arg1, arg2, arg3);
}
