// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {usage} from '../models';
import {time} from '../models';

export function Close():Promise<void>;

export function DeleteModelPricing(arg1:string):Promise<void>;

export function GetDailyTrends(arg1:usage.TrendFilter):Promise<Array<usage.DailyTrendPoint>>;

export function GetModelPricing():Promise<Array<usage.ModelPricing>>;

export function GetModelStats(arg1:usage.StatFilter):Promise<Array<usage.ModelStat>>;

export function GetProviderStats(arg1:usage.StatFilter):Promise<Array<usage.ProviderStat>>;

export function GetRequestLogs(arg1:usage.LogFilter):Promise<Array<usage.UsageRecord>>;

export function GetSyncState():Promise<Array<usage.SyncState>>;

export function GetUnknownModels():Promise<Array<usage.UnknownModel>>;

export function GetUsageSummary(arg1:usage.SummaryFilter):Promise<usage.Summary>;

export function Load():Promise<void>;

export function Pricing():Promise<usage.PricingService>;

export function Record(arg1:usage.UsageEvent):Promise<boolean>;

export function RecordForce(arg1:usage.UsageEvent):Promise<void>;

export function ResetModelPricing():Promise<void>;

export function StartBackgroundSync(arg1:time.Duration):Promise<void>;

export function SyncAll():Promise<void>;

export function SyncSessionUsage():Promise<usage.SyncResult>;

export function UpsertModelPricing(arg1:usage.ModelPricing):Promise<void>;
