// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['usage']['Service']['Close']();
}

export function DeleteModelPricing(arg1) {
  return window['go']['usage']['Service']['DeleteModelPricing'](arg1);
}

export function GetDailyTrends(arg1) {
  return window['go']['usage']['Service']['GetDailyTrends'](arg1);
}

export function GetModelPricing() {
  return window['go']['usage']['Service']['GetModelPricing']();
}

export function GetModelStats(arg1) {
  return window['go']['usage']['Service']['GetModelStats'](arg1);
}

export function GetProviderStats(arg1) {
  return window['go']['usage']['Service']['GetProviderStats'](arg1);
}

export function GetRequestLogs(arg1) {
  return window['go']['usage']['Service']['GetRequestLogs'](arg1);
}

export function GetSyncState() {
  return window['go']['usage']['Service']['GetSyncState']();
}

export function GetUnknownModels() {
  return window['go']['usage']['Service']['GetUnknownModels']();
}

export function GetUsageSummary(arg1) {
  return window['go']['usage']['Service']['GetUsageSummary'](arg1);
}

export function Load() {
  return window['go']['usage']['Service']['Load']();
}

export function Pricing() {
  return window['go']['usage']['Service']['Pricing']();
}

export function Record(arg1) {
  return window['go']['usage']['Service']['Record'](arg1);
}

export function RecordForce(arg1) {
  return window['go']['usage']['Service']['RecordForce'](arg1);
}

export function ResetModelPricing() {
  return window['go']['usage']['Service']['ResetModelPricing']();
}

export function StartBackgroundSync(arg1) {
  return window['go']['usage']['Service']['StartBackgroundSync'](arg1);
}

export function SyncAll() {
  return window['go']['usage']['Service']['SyncAll']();
}

export function SyncSessionUsage() {
  return window['go']['usage']['Service']['SyncSessionUsage']();
}

export function UpsertModelPricing(arg1) {
  return window['go']['usage']['Service']['UpsertModelPricing'](arg1);
}
