// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {amagi} from '../models';

export function DeleteModelPreset(arg1:string):Promise<void>;

export function DeleteSubPreset(arg1:string,arg2:string):Promise<void>;

export function GetModelPreset(arg1:string):Promise<amagi.ModelPresetGroup>;

export function GetModelPresets():Promise<Record<string, amagi.ModelPresetGroup>>;

export function GetSettings():Promise<amagi.AmagiSettings>;

export function GetSettingsJSON():Promise<string>;

export function GetSubPreset(arg1:string,arg2:string):Promise<amagi.AmagiModelPreset>;

export function Load():Promise<void>;

export function RenameModelPreset(arg1:string,arg2:string):Promise<void>;

export function Save():Promise<void>;

export function SaveModelPreset(arg1:string,arg2:amagi.ModelPresetGroup):Promise<void>;

export function SaveSettingsJSON(arg1:string):Promise<void>;

export function SaveSubPreset(arg1:string,arg2:string,arg3:amagi.AmagiModelPreset):Promise<void>;

export function SetAdvisorModel(arg1:string):Promise<void>;

export function SetAlwaysThinkingEnabled(arg1:boolean):Promise<void>;

export function SetAvailableModels(arg1:Array<string>):Promise<void>;

export function SetEffortLevel(arg1:string):Promise<void>;

export function SetModel(arg1:string):Promise<void>;
