// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModelPreset(arg1) {
  return window['go']['amagi']['Service']['DeleteModelPreset'](arg1);
}

export function DeleteSubPreset(arg1, arg2) {
  return window['go']['amagi']['Service']['DeleteSubPreset'](arg1, arg2);
}

export function GetModelPreset(arg1) {
  return window['go']['amagi']['Service']['GetModelPreset'](arg1);
}

export function GetModelPresets() {
  return window['go']['amagi']['Service']['GetModelPresets']();
}

export function GetSettings() {
  return window['go']['amagi']['Service']['GetSettings']();
}

export function GetSettingsJSON() {
  return window['go']['amagi']['Service']['GetSettingsJSON']();
}

export function GetSubPreset(arg1, arg2) {
  return window['go']['amagi']['Service']['GetSubPreset'](arg1, arg2);
}

export function Load() {
  return window['go']['amagi']['Service']['Load']();
}

export function RenameModelPreset(arg1, arg2) {
  return window['go']['amagi']['Service']['RenameModelPreset'](arg1, arg2);
}

export function Save() {
  return window['go']['amagi']['Service']['Save']();
}

export function SaveModelPreset(arg1, arg2) {
  return window['go']['amagi']['Service']['SaveModelPreset'](arg1, arg2);
}

export function SaveSettingsJSON(arg1) {
  return window['go']['amagi']['Service']['SaveSettingsJSON'](arg1);
}

export function SaveSubPreset(arg1, arg2, arg3) {
  return window['go']['amagi']['Service']['SaveSubPreset'](arg1, arg2, arg3);
}

export function SetAdvisorModel(arg1) {
  return window['go']['amagi']['Service']['SetAdvisorModel'](arg1);
}

export function SetAlwaysThinkingEnabled(arg1) {
  return window['go']['amagi']['Service']['SetAlwaysThinkingEnabled'](arg1);
}

export function SetAvailableModels(arg1) {
  return window['go']['amagi']['Service']['SetAvailableModels'](arg1);
}

export function SetEffortLevel(arg1) {
  return window['go']['amagi']['Service']['SetEffortLevel'](arg1);
}

export function SetModel(arg1) {
  return window['go']['amagi']['Service']['SetModel'](arg1);
}
