// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMarketplace(arg1) {
  return window['go']['codexplugin']['Service']['AddMarketplace'](arg1);
}

export function GetPluginDetails(arg1) {
  return window['go']['codexplugin']['Service']['GetPluginDetails'](arg1);
}

export function InstallPlugin(arg1) {
  return window['go']['codexplugin']['Service']['InstallPlugin'](arg1);
}

export function ListAvailablePlugins() {
  return window['go']['codexplugin']['Service']['ListAvailablePlugins']();
}

export function ListMarketplaces() {
  return window['go']['codexplugin']['Service']['ListMarketplaces']();
}

export function ListPlugins(arg1) {
  return window['go']['codexplugin']['Service']['ListPlugins'](arg1);
}

export function RefreshPlugins() {
  return window['go']['codexplugin']['Service']['RefreshPlugins']();
}

export function RemoveMarketplace(arg1) {
  return window['go']['codexplugin']['Service']['RemoveMarketplace'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['codexplugin']['Service']['SetPluginEnabled'](arg1, arg2);
}

export function SetPluginSubItemEnabled(arg1, arg2, arg3, arg4) {
  return window['go']['codexplugin']['Service']['SetPluginSubItemEnabled'](arg1, arg2, arg3, arg4);
}

export function UninstallPlugin(arg1) {
  return window['go']['codexplugin']['Service']['UninstallPlugin'](arg1);
}

export function UpgradeMarketplace(arg1) {
  return window['go']['codexplugin']['Service']['UpgradeMarketplace'](arg1);
}
