// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codexplugin} from '../models';

export function AddMarketplace(arg1:codexplugin.AddMarketplaceRequest):Promise<codexplugin.CommandResult>;

export function GetPluginDetails(arg1:codexplugin.PluginSelector):Promise<codexplugin.CodexPluginDetail>;

export function InstallPlugin(arg1:codexplugin.PluginSelector):Promise<codexplugin.CommandResult>;

export function ListAvailablePlugins():Promise<Array<codexplugin.CodexAvailablePlugin>>;

export function ListMarketplaces():Promise<Array<codexplugin.CodexMarketplace>>;

export function ListPlugins(arg1:string):Promise<Array<codexplugin.CodexPlugin>>;

export function RefreshPlugins():Promise<codexplugin.CodexPluginsData>;

export function RemoveMarketplace(arg1:string):Promise<codexplugin.CommandResult>;

export function SetPluginEnabled(arg1:codexplugin.PluginSelector,arg2:boolean):Promise<codexplugin.CommandResult>;

export function SetPluginSubItemEnabled(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UninstallPlugin(arg1:codexplugin.PluginSelector):Promise<codexplugin.CommandResult>;

export function UpgradeMarketplace(arg1:string):Promise<codexplugin.CommandResult>;
