// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function AddSavedWorkDir(arg1:string,arg2:string):Promise<void>;

export function AddShellPath(arg1:settings.ShellEntry):Promise<void>;

export function GetDashboardDefaults():Promise<settings.DashboardDefaults>;

export function GetGitHubToken():Promise<string>;

export function GetMobileWebRoot():Promise<string>;

export function GetRemoteHost():Promise<string>;

export function GetRemotePort():Promise<number>;

export function GetSavedWorkDirs():Promise<Array<settings.WorkDirEntry>>;

export function GetSettings():Promise<settings.AppSettings>;

export function GetShellPaths():Promise<Array<settings.ShellEntry>>;

export function GetTerminalSettings():Promise<settings.TerminalSettings>;

export function Load():Promise<void>;

export function RemoveSavedWorkDir(arg1:string):Promise<void>;

export function RemoveShellPath(arg1:string):Promise<void>;

export function Save():Promise<void>;

export function SetDashboardDefaults(arg1:settings.DashboardDefaults):Promise<void>;

export function SetGitHubToken(arg1:string):Promise<void>;

export function SetMobileWebRoot(arg1:string):Promise<void>;

export function SetRemoteHost(arg1:string):Promise<void>;

export function SetRemotePort(arg1:number):Promise<void>;

export function SetTerminalSettings(arg1:settings.TerminalSettings):Promise<void>;
