// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddShellPath(arg1) {
  return window['go']['settings']['Service']['AddShellPath'](arg1);
}

export function GetDashboardDefaults() {
  return window['go']['settings']['Service']['GetDashboardDefaults']();
}

export function GetGitHubToken() {
  return window['go']['settings']['Service']['GetGitHubToken']();
}

export function GetMobileWebRoot() {
  return window['go']['settings']['Service']['GetMobileWebRoot']();
}

export function GetRemotePort() {
  return window['go']['settings']['Service']['GetRemotePort']();
}

export function GetSettings() {
  return window['go']['settings']['Service']['GetSettings']();
}

export function GetShellPaths() {
  return window['go']['settings']['Service']['GetShellPaths']();
}

export function GetTerminalSettings() {
  return window['go']['settings']['Service']['GetTerminalSettings']();
}

export function Load() {
  return window['go']['settings']['Service']['Load']();
}

export function RemoveShellPath(arg1) {
  return window['go']['settings']['Service']['RemoveShellPath'](arg1);
}

export function Save() {
  return window['go']['settings']['Service']['Save']();
}

export function SetDashboardDefaults(arg1) {
  return window['go']['settings']['Service']['SetDashboardDefaults'](arg1);
}

export function SetGitHubToken(arg1) {
  return window['go']['settings']['Service']['SetGitHubToken'](arg1);
}

export function SetMobileWebRoot(arg1) {
  return window['go']['settings']['Service']['SetMobileWebRoot'](arg1);
}

export function SetRemotePort(arg1) {
  return window['go']['settings']['Service']['SetRemotePort'](arg1);
}

export function SetTerminalSettings(arg1) {
  return window['go']['settings']['Service']['SetTerminalSettings'](arg1);
}
