// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';

export function AddMarketplace(arg1:string):Promise<plugin.CommandResult>;

export function DisablePlugin(arg1:string):Promise<plugin.CommandResult>;

export function EnablePlugin(arg1:string):Promise<plugin.CommandResult>;

export function GetAvailablePlugins():Promise<Array<any>>;

export function GetInstalledPlugins():Promise<Array<plugin.InstalledPlugin>>;

export function GetMarketplaces():Promise<Array<plugin.Marketplace>>;

export function GetPluginDetail(arg1:string):Promise<plugin.PluginDetail>;

export function InstallPlugin(arg1:string):Promise<plugin.CommandResult>;

export function RefreshPlugins():Promise<void>;

export function RemoveMarketplace(arg1:string):Promise<plugin.CommandResult>;

export function UninstallPlugin(arg1:string):Promise<plugin.CommandResult>;

export function UpdateMarketplace(arg1:string):Promise<plugin.CommandResult>;

export function UpdatePlugin(arg1:string):Promise<plugin.CommandResult>;
