// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMarketplace(arg1) {
  return window['go']['plugin']['Service']['AddMarketplace'](arg1);
}

export function DisablePlugin(arg1) {
  return window['go']['plugin']['Service']['DisablePlugin'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['plugin']['Service']['EnablePlugin'](arg1);
}

export function GetAvailablePlugins() {
  return window['go']['plugin']['Service']['GetAvailablePlugins']();
}

export function GetInstalledPlugins() {
  return window['go']['plugin']['Service']['GetInstalledPlugins']();
}

export function GetMarketplaces() {
  return window['go']['plugin']['Service']['GetMarketplaces']();
}

export function GetPluginDetail(arg1) {
  return window['go']['plugin']['Service']['GetPluginDetail'](arg1);
}

export function InstallPlugin(arg1) {
  return window['go']['plugin']['Service']['InstallPlugin'](arg1);
}

export function RefreshPlugins() {
  return window['go']['plugin']['Service']['RefreshPlugins']();
}

export function RemoveMarketplace(arg1) {
  return window['go']['plugin']['Service']['RemoveMarketplace'](arg1);
}

export function UninstallPlugin(arg1) {
  return window['go']['plugin']['Service']['UninstallPlugin'](arg1);
}

export function UpdateMarketplace(arg1) {
  return window['go']['plugin']['Service']['UpdateMarketplace'](arg1);
}

export function UpdatePlugin(arg1) {
  return window['go']['plugin']['Service']['UpdatePlugin'](arg1);
}
