// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeRemoteSecurityHealth(arg1) {
  return window['go']['main']['App']['AcknowledgeRemoteSecurityHealth'](arg1);
}

export function AddProxyBackendURL(arg1) {
  return window['go']['main']['App']['AddProxyBackendURL'](arg1);
}

export function AddSavedWorkDir(arg1, arg2) {
  return window['go']['main']['App']['AddSavedWorkDir'](arg1, arg2);
}

export function AddUrlToHistory(arg1, arg2) {
  return window['go']['main']['App']['AddUrlToHistory'](arg1, arg2);
}

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function CancelRemotePairingWindow(arg1) {
  return window['go']['main']['App']['CancelRemotePairingWindow'](arg1);
}

export function CheckClaudeConfig() {
  return window['go']['main']['App']['CheckClaudeConfig']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckTool(arg1) {
  return window['go']['main']['App']['CheckTool'](arg1);
}

export function CleanClaudeInstall(arg1) {
  return window['go']['main']['App']['CleanClaudeInstall'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearStoppedSessions() {
  return window['go']['main']['App']['ClearStoppedSessions']();
}

export function ClearStoppedSessionsDetailed() {
  return window['go']['main']['App']['ClearStoppedSessionsDetailed']();
}

export function ConfirmExternalCleanupRecovery(arg1, arg2) {
  return window['go']['main']['App']['ConfirmExternalCleanupRecovery'](arg1, arg2);
}

export function CreateRemotePairingWindow(arg1) {
  return window['go']['main']['App']['CreateRemotePairingWindow'](arg1);
}

export function DeleteEnvVar(arg1) {
  return window['go']['main']['App']['DeleteEnvVar'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteTerminalPreset(arg1, arg2) {
  return window['go']['main']['App']['DeleteTerminalPreset'](arg1, arg2);
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function ExportConfigToFile() {
  return window['go']['main']['App']['ExportConfigToFile']();
}

export function ExportEnvVars() {
  return window['go']['main']['App']['ExportEnvVars']();
}

export function ExportEnvVarsToFile() {
  return window['go']['main']['App']['ExportEnvVarsToFile']();
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function FixClaudeConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['FixClaudeConfig'](arg1, arg2, arg3);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCodexGlobalHeadroom() {
  return window['go']['main']['App']['GetCodexGlobalHeadroom']();
}

export function GetConfigService() {
  return window['go']['main']['App']['GetConfigService']();
}

export function GetEnvCheckOperationState() {
  return window['go']['main']['App']['GetEnvCheckOperationState']();
}

export function GetEnvCheckSnapshot() {
  return window['go']['main']['App']['GetEnvCheckSnapshot']();
}

export function GetEnvCheckStatus() {
  return window['go']['main']['App']['GetEnvCheckStatus']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetEnvVarsGlobalSyncStatus() {
  return window['go']['main']['App']['GetEnvVarsGlobalSyncStatus']();
}

export function GetEnvVarsJSON() {
  return window['go']['main']['App']['GetEnvVarsJSON']();
}

export function GetExternalCleanupRecoveryStatus() {
  return window['go']['main']['App']['GetExternalCleanupRecoveryStatus']();
}

export function GetGitHubToken() {
  return window['go']['main']['App']['GetGitHubToken']();
}

export function GetHeadroomPerfByClient() {
  return window['go']['main']['App']['GetHeadroomPerfByClient']();
}

export function GetHeadroomSavings() {
  return window['go']['main']['App']['GetHeadroomSavings']();
}

export function GetKeyDiagnostics() {
  return window['go']['main']['App']['GetKeyDiagnostics']();
}

export function GetLogFileContent(arg1) {
  return window['go']['main']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetLogSources() {
  return window['go']['main']['App']['GetLogSources']();
}

export function GetLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4);
}

export function GetMergedTerminalPresets(arg1) {
  return window['go']['main']['App']['GetMergedTerminalPresets'](arg1);
}

export function GetOpenCodeConfig() {
  return window['go']['main']['App']['GetOpenCodeConfig']();
}

export function GetOpenCodeConfigPath() {
  return window['go']['main']['App']['GetOpenCodeConfigPath']();
}

export function GetOutputHistorySnapshot(arg1) {
  return window['go']['main']['App']['GetOutputHistorySnapshot'](arg1);
}

export function GetPathsService() {
  return window['go']['main']['App']['GetPathsService']();
}

export function GetPlatformCapabilities() {
  return window['go']['main']['App']['GetPlatformCapabilities']();
}

export function GetProviderExportJSON(arg1) {
  return window['go']['main']['App']['GetProviderExportJSON'](arg1);
}

export function GetProvidersByType(arg1) {
  return window['go']['main']['App']['GetProvidersByType'](arg1);
}

export function GetProxyBackendURLHistory() {
  return window['go']['main']['App']['GetProxyBackendURLHistory']();
}

export function GetPtyDimensions(arg1) {
  return window['go']['main']['App']['GetPtyDimensions'](arg1);
}

export function GetRemotePairingWindow() {
  return window['go']['main']['App']['GetRemotePairingWindow']();
}

export function GetRemoteSecurityHealth() {
  return window['go']['main']['App']['GetRemoteSecurityHealth']();
}

export function GetRemoteStatus() {
  return window['go']['main']['App']['GetRemoteStatus']();
}

export function GetRemoteToken() {
  return window['go']['main']['App']['GetRemoteToken']();
}

export function GetRemoteWebUIStatus() {
  return window['go']['main']['App']['GetRemoteWebUIStatus']();
}

export function GetSavedWorkDirs() {
  return window['go']['main']['App']['GetSavedWorkDirs']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettingsService() {
  return window['go']['main']['App']['GetSettingsService']();
}

export function GetStartupWarnings() {
  return window['go']['main']['App']['GetStartupWarnings']();
}

export function GetTerminalPresets(arg1) {
  return window['go']['main']['App']['GetTerminalPresets'](arg1);
}

export function GetUrlHistory(arg1) {
  return window['go']['main']['App']['GetUrlHistory'](arg1);
}

export function HeadroomGetPort() {
  return window['go']['main']['App']['HeadroomGetPort']();
}

export function HeadroomGetStatus() {
  return window['go']['main']['App']['HeadroomGetStatus']();
}

export function HeadroomIsRunning() {
  return window['go']['main']['App']['HeadroomIsRunning']();
}

export function HeadroomStart(arg1) {
  return window['go']['main']['App']['HeadroomStart'](arg1);
}

export function HeadroomStop() {
  return window['go']['main']['App']['HeadroomStop']();
}

export function ImportConfigFromFile() {
  return window['go']['main']['App']['ImportConfigFromFile']();
}

export function ImportEnvVars(arg1) {
  return window['go']['main']['App']['ImportEnvVars'](arg1);
}

export function ImportEnvVarsFromFile() {
  return window['go']['main']['App']['ImportEnvVarsFromFile']();
}

export function InstallClaudeWithMethod(arg1) {
  return window['go']['main']['App']['InstallClaudeWithMethod'](arg1);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function LaunchCodexSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LaunchCodexSession'](arg1, arg2, arg3, arg4, arg5);
}

export function LaunchOpenCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LaunchOpenCode'](arg1, arg2, arg3, arg4, arg5);
}

export function LaunchPiSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LaunchPiSession'](arg1, arg2, arg3, arg4, arg5);
}

export function LaunchSession(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['LaunchSession'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListRemoteDevices() {
  return window['go']['main']['App']['ListRemoteDevices']();
}

export function ListRemoteSecurityEvents(arg1) {
  return window['go']['main']['App']['ListRemoteSecurityEvents'](arg1);
}

export function MigrateProviderPresetsToTerminal() {
  return window['go']['main']['App']['MigrateProviderPresetsToTerminal']();
}

export function OpenFileInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1, arg2);
}

export function OpenRemoteWebUI() {
  return window['go']['main']['App']['OpenRemoteWebUI']();
}

export function ProxyAddRule(arg1) {
  return window['go']['main']['App']['ProxyAddRule'](arg1);
}

export function ProxyDeleteRule(arg1) {
  return window['go']['main']['App']['ProxyDeleteRule'](arg1);
}

export function ProxyGetLogs() {
  return window['go']['main']['App']['ProxyGetLogs']();
}

export function ProxyGetPort() {
  return window['go']['main']['App']['ProxyGetPort']();
}

export function ProxyGetRules() {
  return window['go']['main']['App']['ProxyGetRules']();
}

export function ProxyGetStatus() {
  return window['go']['main']['App']['ProxyGetStatus']();
}

export function ProxyIsRunning() {
  return window['go']['main']['App']['ProxyIsRunning']();
}

export function ProxyLoadRules(arg1) {
  return window['go']['main']['App']['ProxyLoadRules'](arg1);
}

export function ProxySaveRules(arg1) {
  return window['go']['main']['App']['ProxySaveRules'](arg1);
}

export function ProxySetRules(arg1) {
  return window['go']['main']['App']['ProxySetRules'](arg1);
}

export function ProxyStart(arg1, arg2) {
  return window['go']['main']['App']['ProxyStart'](arg1, arg2);
}

export function ProxyStop() {
  return window['go']['main']['App']['ProxyStop']();
}

export function ProxyUpdateRule(arg1) {
  return window['go']['main']['App']['ProxyUpdateRule'](arg1);
}

export function PtyResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['PtyResize'](arg1, arg2, arg3);
}

export function PtyWrite(arg1, arg2) {
  return window['go']['main']['App']['PtyWrite'](arg1, arg2);
}

export function PtyWriteLarge(arg1, arg2) {
  return window['go']['main']['App']['PtyWriteLarge'](arg1, arg2);
}

export function QuickLaunch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QuickLaunch'](arg1, arg2, arg3, arg4);
}

export function RegenerateRemoteToken() {
  return window['go']['main']['App']['RegenerateRemoteToken']();
}

export function RemoveProxyBackendURL(arg1) {
  return window['go']['main']['App']['RemoveProxyBackendURL'](arg1);
}

export function RemoveSavedWorkDir(arg1) {
  return window['go']['main']['App']['RemoveSavedWorkDir'](arg1);
}

export function RemoveSession(arg1) {
  return window['go']['main']['App']['RemoveSession'](arg1);
}

export function RemoveUrlFromHistory(arg1, arg2) {
  return window['go']['main']['App']['RemoveUrlFromHistory'](arg1, arg2);
}

export function ResolveTerminalPreset(arg1, arg2) {
  return window['go']['main']['App']['ResolveTerminalPreset'](arg1, arg2);
}

export function RevokeRemoteDevice(arg1, arg2) {
  return window['go']['main']['App']['RevokeRemoteDevice'](arg1, arg2);
}

export function RunEnvCheck() {
  return window['go']['main']['App']['RunEnvCheck']();
}

export function RunEnvFixAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunEnvFixAction'](arg1, arg2, arg3);
}

export function SaveAllConfig() {
  return window['go']['main']['App']['SaveAllConfig']();
}

export function SaveClipboardImage(arg1) {
  return window['go']['main']['App']['SaveClipboardImage'](arg1);
}

export function SaveEnvVarsJSON(arg1) {
  return window['go']['main']['App']['SaveEnvVarsJSON'](arg1);
}

export function SaveOpenCodeConfig(arg1) {
  return window['go']['main']['App']['SaveOpenCodeConfig'](arg1);
}

export function SaveProviderFromJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderFromJSON'](arg1, arg2);
}

export function SaveTerminalPreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTerminalPreset'](arg1, arg2, arg3);
}

export function SetCodexGlobalHeadroom(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCodexGlobalHeadroom'](arg1, arg2, arg3);
}

export function SetEnvVar(arg1, arg2) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2);
}

export function SetEnvVarsGlobalSyncEnabled(arg1) {
  return window['go']['main']['App']['SetEnvVarsGlobalSyncEnabled'](arg1);
}

export function SetGitHubToken(arg1) {
  return window['go']['main']['App']['SetGitHubToken'](arg1);
}

export function SetPluginSubItemEnabled(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetPluginSubItemEnabled'](arg1, arg2, arg3, arg4);
}

export function SetProxyBackendURL(arg1) {
  return window['go']['main']['App']['SetProxyBackendURL'](arg1);
}

export function SetRemoteEndpoint(arg1, arg2) {
  return window['go']['main']['App']['SetRemoteEndpoint'](arg1, arg2);
}

export function SetRemoteHost(arg1) {
  return window['go']['main']['App']['SetRemoteHost'](arg1);
}

export function SetRemotePort(arg1) {
  return window['go']['main']['App']['SetRemotePort'](arg1);
}

export function StartInstallClaudeWithMethodAsync(arg1) {
  return window['go']['main']['App']['StartInstallClaudeWithMethodAsync'](arg1);
}

export function StartInstallToolAsync(arg1) {
  return window['go']['main']['App']['StartInstallToolAsync'](arg1);
}

export function StartUpdateToolAsync(arg1) {
  return window['go']['main']['App']['StartUpdateToolAsync'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function ToggleRemoteServer(arg1) {
  return window['go']['main']['App']['ToggleRemoteServer'](arg1);
}

export function UninstallClaudeCode(arg1) {
  return window['go']['main']['App']['UninstallClaudeCode'](arg1);
}

export function UpdateProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2, arg3);
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}
