// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxyBackendURL(arg1) {
  return window['go']['main']['App']['AddProxyBackendURL'](arg1);
}

export function AddUrlToHistory(arg1, arg2) {
  return window['go']['main']['App']['AddUrlToHistory'](arg1, arg2);
}

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearStoppedSessions() {
  return window['go']['main']['App']['ClearStoppedSessions']();
}

export function DeleteEnvVar(arg1) {
  return window['go']['main']['App']['DeleteEnvVar'](arg1);
}

export function DownloadAndApplyUpdate() {
  return window['go']['main']['App']['DownloadAndApplyUpdate']();
}

export function ExportConfigToFile() {
  return window['go']['main']['App']['ExportConfigToFile']();
}

export function ExportEnvVars() {
  return window['go']['main']['App']['ExportEnvVars']();
}

export function ExportEnvVarsToFile() {
  return window['go']['main']['App']['ExportEnvVarsToFile']();
}

export function ExportLogs() {
  return window['go']['main']['App']['ExportLogs']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConfigService() {
  return window['go']['main']['App']['GetConfigService']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetEnvVarsJSON() {
  return window['go']['main']['App']['GetEnvVarsJSON']();
}

export function GetGitHubToken() {
  return window['go']['main']['App']['GetGitHubToken']();
}

export function GetKeyDiagnostics() {
  return window['go']['main']['App']['GetKeyDiagnostics']();
}

export function GetLogFileContent(arg1) {
  return window['go']['main']['App']['GetLogFileContent'](arg1);
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetLogSources() {
  return window['go']['main']['App']['GetLogSources']();
}

export function GetLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4);
}

export function GetOutputHistory(arg1) {
  return window['go']['main']['App']['GetOutputHistory'](arg1);
}

export function GetPathsService() {
  return window['go']['main']['App']['GetPathsService']();
}

export function GetProviderExportJSON(arg1) {
  return window['go']['main']['App']['GetProviderExportJSON'](arg1);
}

export function GetProvidersByType(arg1) {
  return window['go']['main']['App']['GetProvidersByType'](arg1);
}

export function GetProxyBackendURLHistory() {
  return window['go']['main']['App']['GetProxyBackendURLHistory']();
}

export function GetPtyDimensions(arg1) {
  return window['go']['main']['App']['GetPtyDimensions'](arg1);
}

export function GetRemoteStatus() {
  return window['go']['main']['App']['GetRemoteStatus']();
}

export function GetRemoteToken() {
  return window['go']['main']['App']['GetRemoteToken']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettingsService() {
  return window['go']['main']['App']['GetSettingsService']();
}

export function GetUrlHistory(arg1) {
  return window['go']['main']['App']['GetUrlHistory'](arg1);
}

export function ImportConfigFromFile() {
  return window['go']['main']['App']['ImportConfigFromFile']();
}

export function ImportEnvVars(arg1) {
  return window['go']['main']['App']['ImportEnvVars'](arg1);
}

export function ImportEnvVarsFromFile() {
  return window['go']['main']['App']['ImportEnvVarsFromFile']();
}

export function LaunchCodexSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LaunchCodexSession'](arg1, arg2, arg3, arg4, arg5);
}

export function LaunchOpenCode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LaunchOpenCode'](arg1, arg2, arg3, arg4);
}

export function LaunchSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['LaunchSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OpenFileInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenFileInEditor'](arg1, arg2);
}

export function PtyResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['PtyResize'](arg1, arg2, arg3);
}

export function PtyWrite(arg1, arg2) {
  return window['go']['main']['App']['PtyWrite'](arg1, arg2);
}

export function PtyWriteLarge(arg1, arg2) {
  return window['go']['main']['App']['PtyWriteLarge'](arg1, arg2);
}

export function QuickLaunch(arg1, arg2, arg3) {
  return window['go']['main']['App']['QuickLaunch'](arg1, arg2, arg3);
}

export function RegenerateRemoteToken() {
  return window['go']['main']['App']['RegenerateRemoteToken']();
}

export function RegisterExitCallback(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterExitCallback'](arg1, arg2, arg3);
}

export function RegisterOutputCallback(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterOutputCallback'](arg1, arg2, arg3);
}

export function RegisterResizeCallback(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterResizeCallback'](arg1, arg2, arg3);
}

export function RemoveProxyBackendURL(arg1) {
  return window['go']['main']['App']['RemoveProxyBackendURL'](arg1);
}

export function RemoveSession(arg1) {
  return window['go']['main']['App']['RemoveSession'](arg1);
}

export function RemoveUrlFromHistory(arg1, arg2) {
  return window['go']['main']['App']['RemoveUrlFromHistory'](arg1, arg2);
}

export function SaveAllConfig() {
  return window['go']['main']['App']['SaveAllConfig']();
}

export function SaveClipboardImage(arg1) {
  return window['go']['main']['App']['SaveClipboardImage'](arg1);
}

export function SaveEnvVarsJSON(arg1) {
  return window['go']['main']['App']['SaveEnvVarsJSON'](arg1);
}

export function SaveProviderFromJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderFromJSON'](arg1, arg2);
}

export function SetEnvVar(arg1, arg2) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2);
}

export function SetGitHubToken(arg1) {
  return window['go']['main']['App']['SetGitHubToken'](arg1);
}

export function SetProxyBackendURL(arg1) {
  return window['go']['main']['App']['SetProxyBackendURL'](arg1);
}

export function SetRemotePort(arg1) {
  return window['go']['main']['App']['SetRemotePort'](arg1);
}

export function SetRemoteHost(arg1) {
  return window['go']['main']['App']['SetRemoteHost'](arg1);
}

export function StopAllSessions() {
  return window['go']['main']['App']['StopAllSessions']();
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function ToggleRemoteServer(arg1) {
  return window['go']['main']['App']['ToggleRemoteServer'](arg1);
}

export function UnregisterExitCallback(arg1, arg2) {
  return window['go']['main']['App']['UnregisterExitCallback'](arg1, arg2);
}

export function UnregisterOutputCallback(arg1, arg2) {
  return window['go']['main']['App']['UnregisterOutputCallback'](arg1, arg2);
}

export function UnregisterResizeCallback(arg1, arg2) {
  return window['go']['main']['App']['UnregisterResizeCallback'](arg1, arg2);
}
