// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {amagi} from '../models';
import {config} from '../models';
import {envvars} from '../models';
import {logging} from '../models';
import {paths} from '../models';
import {session} from '../models';
import {settings} from '../models';

export function AddProxyBackendURL(arg1:string):Promise<void>;

export function AddUrlToHistory(arg1:string,arg2:string):Promise<void>;

export function BrowseDirectory():Promise<string>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ClearLogs():Promise<void>;

export function ClearStoppedSessions():Promise<number>;

export function DeleteAmagiModelPreset(arg1:string):Promise<void>;

export function DeleteAmagiSubPreset(arg1:string,arg2:string):Promise<void>;

export function DeleteEnvVar(arg1:string):Promise<void>;

export function DownloadAndApplyUpdate():Promise<void>;

export function ExportConfigToFile():Promise<string>;

export function ExportEnvVars():Promise<string>;

export function ExportEnvVarsToFile():Promise<void>;

export function ExportLogs():Promise<string>;

export function GetAmagiSettings():Promise<amagi.AmagiSettings>;

export function GetAmagiSettingsJSON():Promise<string>;

export function GetAmagiSubPreset(arg1:string,arg2:string):Promise<amagi.AmagiModelPreset>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetConfigService():Promise<config.ConfigService>;

export function GetEnvVars():Promise<Array<envvars.EnvVar>>;

export function GetEnvVarsJSON():Promise<string>;

export function GetGitHubToken():Promise<string>;

export function GetKeyDiagnostics():Promise<Record<string, Record<string, string>>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogSources():Promise<Array<string>>;

export function GetLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<logging.Entry>>;

export function GetOpenCodeConfig():Promise<string>;

export function GetOpenCodeConfigPath():Promise<string>;

export function GetOutputHistory(arg1:string):Promise<Array<number>>;

export function GetPathsService():Promise<paths.PathsService>;

export function GetProviderExportJSON(arg1:string):Promise<string>;

export function GetProvidersByType(arg1:string):Promise<Record<string, config.Provider>>;

export function GetProxyBackendURLHistory():Promise<Array<string>>;

export function GetTerminalPresets(arg1:string):Promise<Record<string, config.TerminalPreset>>;

export function GetMergedTerminalPresets(arg1:string):Promise<Array<config.MergedTerminalPreset>>;

export function SaveTerminalPreset(arg1:string,arg2:string,arg3:config.TerminalPreset):Promise<void>;

export function DeleteTerminalPreset(arg1:string,arg2:string):Promise<void>;

export function MigrateProviderPresetsToTerminal():Promise<number>;

export function GetPtyDimensions(arg1:string):Promise<number>;

export function GetRemoteStatus():Promise<Record<string, any>>;

export function GetRemoteToken():Promise<string>;

export function GetSession(arg1:string):Promise<session.SessionInfo>;

export function GetSessions():Promise<Array<session.SessionInfo>>;

export function GetSettingsService():Promise<settings.Service>;

export function GetStartupWarnings():Promise<Array<string>>;

export function GetUrlHistory(arg1:string):Promise<Array<string>>;

export function ImportConfigFromFile():Promise<string>;

export function ImportEnvVars(arg1:string):Promise<void>;

export function ImportEnvVarsFromFile():Promise<void>;

export function LaunchAmagiCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function LaunchCodexSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function LaunchOpenCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function LaunchSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<string>;

export function OpenFileInEditor(arg1:string,arg2:number):Promise<void>;

export function PtyResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PtyWrite(arg1:string,arg2:string):Promise<void>;

export function PtyWriteLarge(arg1:string,arg2:string):Promise<void>;

export function QuickLaunch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RegenerateRemoteToken():Promise<string>;

export function RegisterExitCallback(arg1:string,arg2:string,arg3:any):Promise<void>;

export function RegisterOutputCallback(arg1:string,arg2:string,arg3:any):Promise<void>;

export function RegisterResizeCallback(arg1:string,arg2:string,arg3:any):Promise<void>;

export function RemoveProxyBackendURL(arg1:string):Promise<void>;

export function RemoveSession(arg1:string):Promise<void>;

export function RemoveUrlFromHistory(arg1:string,arg2:string):Promise<void>;

export function RenameAmagiModelPreset(arg1:string,arg2:string):Promise<void>;

export function SaveAllConfig():Promise<void>;

export function SaveAmagiModelPreset(arg1:string,arg2:amagi.ModelPresetGroup):Promise<void>;

export function SaveAmagiSettingsJSON(arg1:string):Promise<void>;

export function SaveAmagiSubPreset(arg1:string,arg2:string,arg3:amagi.AmagiModelPreset):Promise<void>;

export function SaveClipboardImage(arg1:string):Promise<string>;

export function SaveEnvVarsJSON(arg1:string):Promise<void>;

export function SaveOpenCodeConfig(arg1:string):Promise<void>;

export function SaveProviderFromJSON(arg1:string,arg2:string):Promise<void>;

export function SetAmagiAvailableModels(arg1:Array<string>):Promise<void>;

export function SetAmagiEffortLevel(arg1:string):Promise<void>;

export function SetAmagiModel(arg1:string):Promise<void>;

export function SetEnvVar(arg1:string,arg2:string):Promise<void>;

export function SetGitHubToken(arg1:string):Promise<void>;

export function SetProxyBackendURL(arg1:string):Promise<void>;

export function SetRemoteHost(arg1:string):Promise<void>;

export function SetRemotePort(arg1:number):Promise<void>;

export function StopAllSessions():Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function ToggleRemoteServer(arg1:boolean):Promise<void>;

export function UnregisterExitCallback(arg1:string,arg2:string):Promise<void>;

export function UnregisterOutputCallback(arg1:string,arg2:string):Promise<void>;

export function UnregisterResizeCallback(arg1:string,arg2:string):Promise<void>;
