// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {remote} from '../models';
import {settings} from '../models';
import {envcheck} from '../models';
import {updater} from '../models';
import {main} from '../models';
import {config} from '../models';
import {envvars} from '../models';
import {headroom} from '../models';
import {logging} from '../models';
import {paths} from '../models';
import {platform} from '../models';
import {session} from '../models';
import {proxy} from '../models';

export function AcknowledgeRemoteSecurityHealth(arg1:string):Promise<remote.SecurityHealthSnapshot>;

export function AddProxyBackendURL(arg1:string):Promise<void>;

export function AddSavedWorkDir(arg1:string,arg2:string):Promise<Array<settings.WorkDirEntry>>;

export function AddUrlToHistory(arg1:string,arg2:string):Promise<void>;

export function BrowseDirectory():Promise<string>;

export function CancelRemotePairingWindow(arg1:number):Promise<boolean>;

export function CheckClaudeConfig():Promise<envcheck.ClaudeConfigStatus>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function CheckTool(arg1:string):Promise<envcheck.CheckStatus>;

export function CleanClaudeInstall(arg1:string):Promise<envcheck.InstallResult>;

export function ClearLogs():Promise<void>;

export function ClearStoppedSessions():Promise<number>;

export function ClearStoppedSessionsDetailed():Promise<main.ClearStoppedSessionsResult>;

export function ConfirmExternalCleanupRecovery(arg1:string,arg2:boolean):Promise<remote.ExternalCleanupRecoveryResult>;

export function CreateRemotePairingWindow(arg1:boolean):Promise<remote.PairingWindowInfo>;

export function DeleteEnvVar(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteTerminalPreset(arg1:string,arg2:string):Promise<void>;

export function DownloadAndApplyUpdate():Promise<void>;

export function ExportConfigToFile():Promise<string>;

export function ExportEnvVars():Promise<string>;

export function ExportEnvVarsToFile():Promise<void>;

export function ExportLogs():Promise<string>;

export function FixClaudeConfig(arg1:string,arg2:string,arg3:string):Promise<envcheck.ConfigFixResult>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetCodexGlobalHeadroom():Promise<main.CodexGlobalHeadroomStatus>;

export function GetConfigService():Promise<config.ConfigService>;

export function GetEnvCheckOperationState():Promise<envcheck.OperationState>;

export function GetEnvCheckSnapshot():Promise<envcheck.EnvCheckSnapshot>;

export function GetEnvCheckStatus():Promise<envcheck.OverallStatus>;

export function GetEnvVars():Promise<Array<envvars.EnvVar>>;

export function GetEnvVarsGlobalSyncStatus():Promise<envvars.GlobalSyncStatus>;

export function GetEnvVarsJSON():Promise<string>;

export function GetExternalCleanupRecoveryStatus():Promise<remote.ExternalCleanupRecoveryStatus>;

export function GetGitHubToken():Promise<string>;

export function GetHeadroomPerfByClient():Promise<Array<headroom.ClientPerfStat>>;

export function GetHeadroomSavings():Promise<headroom.SavingsReport>;

export function GetKeyDiagnostics():Promise<Record<string, Record<string, string>>>;

export function GetLogFileContent(arg1:string):Promise<string>;

export function GetLogFiles():Promise<Array<string>>;

export function GetLogSources():Promise<Array<string>>;

export function GetLogs(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<logging.Entry>>;

export function GetMergedTerminalPresets(arg1:string):Promise<Array<config.MergedTerminalPreset>>;

export function GetOpenCodeConfig():Promise<string>;

export function GetOpenCodeConfigPath():Promise<string>;

export function GetOutputHistorySnapshot(arg1:string):Promise<string>;

export function GetPathsService():Promise<paths.PathsService>;

export function GetPlatformCapabilities():Promise<platform.PlatformCapabilities>;

export function GetProviderExportJSON(arg1:string):Promise<string>;

export function GetProvidersByType(arg1:string):Promise<Record<string, config.Provider>>;

export function GetProxyBackendURLHistory():Promise<Array<string>>;

export function GetPtyDimensions(arg1:string):Promise<number>;

export function GetRemotePairingWindow():Promise<remote.PairingWindowStatus>;

export function GetRemoteSecurityHealth():Promise<remote.SecurityHealthSnapshot>;

export function GetRemoteStatus():Promise<Record<string, any>>;

export function GetRemoteToken():Promise<string>;

export function GetRemoteWebUIStatus():Promise<main.RemoteWebUIStatusResult>;

export function GetSavedWorkDirs():Promise<Array<settings.WorkDirEntry>>;

export function GetSession(arg1:string):Promise<session.SessionInfo>;

export function GetSessions():Promise<Array<session.SessionInfo>>;

export function GetSettingsService():Promise<settings.Service>;

export function GetStartupWarnings():Promise<Array<string>>;

export function GetTerminalPresets(arg1:string):Promise<Record<string, config.TerminalPreset>>;

export function GetUrlHistory(arg1:string):Promise<Array<string>>;

export function HeadroomGetPort():Promise<number>;

export function HeadroomGetStatus():Promise<headroom.HeadroomStatus>;

export function HeadroomIsRunning():Promise<boolean>;

export function HeadroomStart(arg1:string):Promise<void>;

export function HeadroomStop():Promise<void>;

export function ImportConfigFromFile():Promise<string>;

export function ImportEnvVars(arg1:string):Promise<void>;

export function ImportEnvVarsFromFile():Promise<void>;

export function InstallClaudeWithMethod(arg1:string):Promise<envcheck.InstallResult>;

export function InstallTool(arg1:string):Promise<envcheck.InstallResult>;

export function LaunchCodexSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function LaunchOpenCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function LaunchPiSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function LaunchSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:string):Promise<string>;

export function ListRemoteDevices():Promise<Array<remote.DeviceInfo>>;

export function ListRemoteSecurityEvents(arg1:number):Promise<Array<remote.SecurityEventRecord>>;

export function MigrateProviderPresetsToTerminal():Promise<number>;

export function OpenFileInEditor(arg1:string,arg2:number):Promise<void>;

export function OpenRemoteWebUI():Promise<main.OpenRemoteWebUIResult>;

export function ProxyAddRule(arg1:proxy.InjectionRule):Promise<void>;

export function ProxyDeleteRule(arg1:string):Promise<void>;

export function ProxyGetLogs():Promise<Array<proxy.InjectionLog>>;

export function ProxyGetPort():Promise<number>;

export function ProxyGetRules():Promise<Array<proxy.InjectionRule>>;

export function ProxyGetStatus():Promise<proxy.ProxyStatus>;

export function ProxyIsRunning():Promise<boolean>;

export function ProxyLoadRules(arg1:string):Promise<void>;

export function ProxySaveRules(arg1:string):Promise<void>;

export function ProxySetRules(arg1:Array<proxy.InjectionRule>):Promise<void>;

export function ProxyStart(arg1:number,arg2:string):Promise<void>;

export function ProxyStop():Promise<void>;

export function ProxyUpdateRule(arg1:proxy.InjectionRule):Promise<void>;

export function PtyResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PtyWrite(arg1:string,arg2:string):Promise<void>;

export function PtyWriteLarge(arg1:string,arg2:string):Promise<void>;

export function QuickLaunch(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function RegenerateRemoteToken():Promise<string>;

export function RemoveProxyBackendURL(arg1:string):Promise<void>;

export function RemoveSavedWorkDir(arg1:string):Promise<Array<settings.WorkDirEntry>>;

export function RemoveSession(arg1:string):Promise<void>;

export function RemoveUrlFromHistory(arg1:string,arg2:string):Promise<void>;

export function ResolveTerminalPreset(arg1:string,arg2:string):Promise<string>;

export function RevokeRemoteDevice(arg1:string,arg2:boolean):Promise<remote.RevokeDeviceResult>;

export function RunEnvCheck():Promise<envcheck.OverallStatus>;

export function RunEnvFixAction(arg1:string,arg2:string,arg3:string):Promise<envcheck.FixActionResult>;

export function SaveAllConfig():Promise<void>;

export function SaveClipboardImage(arg1:string):Promise<string>;

export function SaveEnvVarsJSON(arg1:string):Promise<void>;

export function SaveOpenCodeConfig(arg1:string):Promise<void>;

export function SaveProviderFromJSON(arg1:string,arg2:string):Promise<void>;

export function SaveTerminalPreset(arg1:string,arg2:string,arg3:config.TerminalPreset):Promise<void>;

export function SetCodexGlobalHeadroom(arg1:boolean,arg2:string,arg3:number):Promise<main.CodexGlobalHeadroomStatus>;

export function SetEnvVar(arg1:string,arg2:string):Promise<void>;

export function SetEnvVarsGlobalSyncEnabled(arg1:boolean):Promise<envvars.GlobalSyncStatus>;

export function SetGitHubToken(arg1:string):Promise<void>;

export function SetPluginSubItemEnabled(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetProxyBackendURL(arg1:string):Promise<void>;

export function SetRemoteEndpoint(arg1:string,arg2:number):Promise<void>;

export function SetRemoteHost(arg1:string):Promise<void>;

export function SetRemotePort(arg1:number):Promise<void>;

export function StartInstallClaudeWithMethodAsync(arg1:string):Promise<envcheck.OperationState>;

export function StartInstallToolAsync(arg1:string):Promise<envcheck.OperationState>;

export function StartUpdateToolAsync(arg1:string):Promise<envcheck.OperationState>;

export function StopSession(arg1:string):Promise<void>;

export function ToggleRemoteServer(arg1:boolean):Promise<void>;

export function UninstallClaudeCode(arg1:string):Promise<envcheck.InstallResult>;

export function UpdateProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateTool(arg1:string):Promise<envcheck.InstallResult>;
