// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPath(arg1) {
  return window['go']['paths']['PathsService']['AddPath'](arg1);
}

export function GetDefaultPath() {
  return window['go']['paths']['PathsService']['GetDefaultPath']();
}

export function GetPaths() {
  return window['go']['paths']['PathsService']['GetPaths']();
}

export function Load() {
  return window['go']['paths']['PathsService']['Load']();
}

export function RemovePath(arg1) {
  return window['go']['paths']['PathsService']['RemovePath'](arg1);
}

export function Save() {
  return window['go']['paths']['PathsService']['Save']();
}

export function SetDefaultPath(arg1) {
  return window['go']['paths']['PathsService']['SetDefaultPath'](arg1);
}

export function UpdateLabel(arg1, arg2) {
  return window['go']['paths']['PathsService']['UpdateLabel'](arg1, arg2);
}

export function ValidatePath(arg1) {
  return window['go']['paths']['PathsService']['ValidatePath'](arg1);
}
