// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {paths} from '../models';

export function AddPath(arg1:paths.PathEntry):Promise<void>;

export function GetDefaultPath():Promise<string>;

export function GetPaths():Promise<Array<paths.PathEntry>>;

export function Load():Promise<void>;

export function RemovePath(arg1:string):Promise<void>;

export function Save():Promise<void>;

export function SetDefaultPath(arg1:string):Promise<void>;

export function UpdateLabel(arg1:string,arg2:string):Promise<void>;

export function ValidatePath(arg1:string):Promise<boolean>;
