// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWebUIStatus(arg1) {
  return window['go']['webui']['Service']['GetWebUIStatus'](arg1);
}

export function Invalidate(arg1) {
  return window['go']['webui']['Service']['Invalidate'](arg1);
}

export function OpenWebPlane(arg1) {
  return window['go']['webui']['Service']['OpenWebPlane'](arg1);
}

export function ProbeWebUI(arg1) {
  return window['go']['webui']['Service']['ProbeWebUI'](arg1);
}

export function RegisterSession(arg1, arg2, arg3, arg4) {
  return window['go']['webui']['Service']['RegisterSession'](arg1, arg2, arg3, arg4);
}

export function RemoveSession(arg1) {
  return window['go']['webui']['Service']['RemoveSession'](arg1);
}
