// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {webui} from '../models';

export function GetWebUIStatus(arg1:string):Promise<webui.Status>;

export function Invalidate(arg1:string):Promise<void>;

export function OpenWebPlane(arg1:string):Promise<string>;

export function ProbeWebUI(arg1:string):Promise<webui.Status>;

export function RegisterSession(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function RemoveSession(arg1:string):Promise<void>;
